#theme: just-the-docs
remote_theme: pmarsceill/just-the-docs

title: Simple Notes
description: Many random notes worth searching for

permalink: pretty
exclude: 
  - Gemfile
  - Gemfile.lock
  - .git
  - .gitignore

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/just-the-docs.png"

# Enable or disable the site search
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Simple Notes on GitHub":
    - "//github.com/akirasy/akirasy.github.io"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Sort order for navigation links
nav_sort: case_sensitive

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2020 akirasy.<br>Distributed under MIT License."

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: false 
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/akirasy/akirasy.github.io"
gh_edit_branch: "master"
gh_edit_view_mode: "tree"

color_scheme: nil

plugins:
  - jekyll-seo-tag

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
